name: humun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dynamic_fonts: ^2.2.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  provider: ^6.1.2
  table_calendar: ^3.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: assets/image/app_logo.png


flutter:
  uses-material-design: true
  assets:
    - assets/image/app_logo.png
    - assets/image/logo.png
    - assets/image/humun.png
    - assets/image/news.png
    - assets/image/test.png
    - assets/image/banner.png
    - assets/image/calendar.png
